---
- name: Collect information and run commands based on user input
  hosts: esxi_hosts
  gather_facts: no
  vars:
    command_file_url: "https://raw.githubusercontent.com/your_github_username/esxi-commands/main/commands.yml"
    esxi_username: ""
    esxi_password: ""

  tasks:
    - name: Prompt for ESXi username
      ansible.builtin.pause:
        prompt: "Enter the ESXi username:"
      register: username_input
    - name: Set ESXi username
      set_fact:
        esxi_username: "{{ username_input.user_input }}"

    - name: Prompt for ESXi password
      ansible.builtin.pause:
        prompt: "Enter the ESXi password:"
        private: yes
      register: password_input
    - name: Set ESXi password
      set_fact:
        esxi_password: "{{ password_input.user_input }}"

    - name: Ensure SSH is enabled on ESXi
      vmware_host_service_manager:
        hostname: "{{ ansible_host }}"
        username: "{{ esxi_username }}"
        password: "{{ esxi_password }}"
        esxi_hostname: "{{ ansible_host }}"
        validate_certs: no
        service_name: TSM-SSH
        state: started
      delegate_to: localhost

    - name: Download command file from GitHub
      ansible.builtin.get_url:
        url: "{{ command_file_url }}"
        dest: "/tmp/commands.yml"

    - name: Load command file
      ansible.builtin.include_vars:
        file: "/tmp/commands.yml"
        name: command_data

    - name: Run commands in a loop until user exits
      block:
        - name: Prompt user to display command list or enter a command
